In [1]:
import pandas as pd

In [2]:
import os

In [ ]:
os.getcwd()

In [ ]:
os.listdir()

In [3]:
arquivo_UF = r"202506Consorcios_UF\202506Consorcios_UF.csv"

In [9]:
df = pd.read_csv(arquivo_UF, sep=";", encoding="Latin-1")

In [10]:
df.head()

,#Data_base,CNPJ_da_Administradora,Nome_da_Administradora,Código_do_segmento,Unidade_da_Federação_do_consorciado,Quantidade_de_consorciados_ativos_contemplados_por_lance,Quantidade_de_consorciados_ativos_contemplados_por_sorteio,Quantidade_de_consorciados_ativos_não_contemplados,Quantidade_de_consorciados_excluídos_contemplados,Quantidade_de_consorciados_excluídos_não_contemplados,Quantidade_de_consorciados_ativos_contemplados_por_lance_no_trimestre,Quantidade_de_consorciados_ativos_contemplados_por_sorteio_no_trimestre,Quantidade_de_consorciados_excluídos_contemplados_no_trimestre,Quantidade_de_adesões_no_trimestre
0,202506,776,ITAÚ ADM DE CONSÓRCIOS LTDA ...,1,AC,17,9,61,13,228,1,0,1,9
1,202506,776,ITAÚ ADM DE CONSÓRCIOS LTDA ...,2,AC,0,1,2,0,0,0,0,0,0
2,202506,776,ITAÚ ADM DE CONSÓRCIOS LTDA ...,3,AC,127,32,191,41,266,5,5,9,23
3,202506,776,ITAÚ ADM DE CONSÓRCIOS LTDA ...,4,AC,87,4,21,3,84,14,0,0,13
4,202506,776,ITAÚ ADM DE CONSÓRCIOS LTDA ...,1,AL,112,52,384,48,805,5,2,2,92